AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation Template for sample lambda function
Parameters:
  Prefix:
    Type: String
    Description: Prefix for the resource name

Resources:
  SampleLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${Prefix}-sample-lambda"
      Description: Lambda function to bootstrap lex session
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Code: ../package
      Role: !GetAtt SampleLambdaRole.Arn
      Timeout: 15
      MemorySize: 256
      Environment:
        Variables:
          LOG_LEVEL: DEBUG
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV2:46

  SampleLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Prefix}-sample-lambda"
      RetentionInDays: 7

  SampleLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Prefix}-sample-lambda-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub "${Prefix}-sample-lambda-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !GetAtt "SampleLambdaLogGroup.Arn"
